// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class MultiplyResult;
@class MultiplyRequest;

@interface MultiplyResult : NSObject
@property(nonatomic, strong, nullable) NSNumber * result;
@end

@interface MultiplyRequest : NSObject
@property(nonatomic, strong, nullable) NSNumber * multiplicand;
@property(nonatomic, strong, nullable) NSNumber * multiplier;
@end

@protocol MultiplyApi
-(nullable MultiplyResult *)multiply:(MultiplyRequest*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void MultiplyApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<MultiplyApi> _Nullable api);

NS_ASSUME_NONNULL_END
